<a href="https://colab.research.google.com/github/YutaOkkotsu0/cv/blob/main/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
gdata = pd.read_csv('./Gender-Data.csv')
gdata

,Gender,SEX,Height (in cm),Weight (in lbs),Hair length (in inches),Beard (1/0),Hijab (1/0),"Skin Color (white,brown,black)","Eye Color (Black,Brown,Other)","Hair Color (brown,black,other)",Bald (1/0),Physical Activities (1/0),Cooking (1/0),Own a pet (1/0),Wear Jewelery (1/0),Hair Dye (1/0),Piercing (1/0),Wear Contact Lens (1/0)
0,Male,0,170,180,3,1,0,brown,black,black,0,1,0,0,0,0,0,0
1,Male,0,184,137,6,1,0,brown,brown,black,0,1,1,0,0,0,0,0
2,Male,0,172,158,5,1,0,brown,brown,black,0,1,0,0,0,0,0,0
3,Male,0,182,195,5,1,0,brown,black,black,0,1,1,0,0,0,0,0
4,Male,0,175,108,3,1,0,brown,black,black,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Male,0,170,140,5,1,0,brown,brown,black,0,1,0,0,0,0,0,1
95,Male,0,160,150,4,1,0,brown,black,black,0,1,0,0,0,0,0,1
96,Male,0,179,141,4,1,0,browm,black,black,0,1,1,0,0,0,0,1
97,Male,0,180,176,4,1,0,brown,brown,black,0,1,1,0,0,0,0,1
98,Male,0,178,158,2,1,0,brown,black,black,0,1,0,0,0,0,0,1

In [13]:
import math
import pandas as pd

data = pd.read_csv('./Gender-Data.csv')
val_k = []
distance = []

def calcDistance(test):
    global distance
    percent_80 = int(0.8 * len(data)) 
    for p in range(percent_80):
        dis = format(math.sqrt((data['Height (in cm)'][p] - test[0])**2 + (data['Weight (in lbs)'][p] - test[1])**2 + (data['Hair length (in inches)'][p] - test[2])**2 ), '.2f')
        distance.append(dis)


def neighbors(k):
    global distance
    global val_k
    while(k != 0):
        for p in range(len(distance)):
            if(distance[p] != -1):
                minimum_val = distance[p]
                index = p
                break

        for q in range(len(distance)):
            if(float(distance[q]) < float(minimum_val) and float(distance[q]) > -1.00):
                minimum_val = distance[q]
                index = q
        val_k.append((minimum_val, index))
        distance[index] = -1
        k = k - 1


def classify():
    global data
    global val_k
    global distance
    
    
    Female = 0
    Male = 0
    
    
    for i in range(len(val_k)):
        if(data['Gender'][val_k[i][1]] == 'Female'):
            Female += 1
        elif(data['Gender'][val_k[i][1]] == 'Male'):

            Male += 1
    
    val_k.clear()
    distance.clear() 
    if(Male > Female):
        print("Test sample is Male")
    elif(Female > Male):
        print("Test sample is Female")
    

def knn(test, k):
    calcDistance(test)
    neighbors(k)
    classify()
        
percent_80 = int(0.8 * len(data))
for p in range(percent_80, len(data)):
    v1 = data['Height (in cm)'][p]
    v2 = data['Weight (in lbs)'][p]
    v3 = data['Hair length (in inches)'][p]
    test = (v1, v2, v3)
    print(test)
    k = 8
    knn(test, k)

(182, 172, 3)
Test sample is Male
(172, 160, 1)
Test sample is Male
(167, 127, 2)
Test sample is Male
(175, 121, 3)
Test sample is Male
(172, 165, 3)
Test sample is Male
(182, 176, 3)
Test sample is Male
(180, 160, 3)
Test sample is Male
(175, 143, 2)
Test sample is Male
(175, 150, 3)
Test sample is Male
(170, 143, 5)
Test sample is Male
(175, 125, 3)
Test sample is Male
(156, 126, 24)
Test sample is Female
(175, 154, 4)
Test sample is Male
(178, 135, 5)
Test sample is Male
(170, 130, 4)
Test sample is Male
(170, 140, 5)
Test sample is Male
(160, 150, 4)
Test sample is Male
(179, 141, 4)
Test sample is Male
(180, 176, 4)
Test sample is Male
(178, 158, 2)
Test sample is Male

In [14]:


print(len(data))
percent_80 = int(0.8*len(data))
print(percent_80)

99
79